server:
  port: 8032

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-a
    api-b:
      path: /api-b/**
      serviceId: service-b